### ISSUE TITLE
Feature-request: download/upload gs.key

### ISSUE THREAD

**Issue by seriyps** [OpenIPC/improver#3]
Hey, cool project!

I believe it would be cool if it would allow downloading and updating the gs.key

Since this is a binary file, I guess it doesn't make sense to allow editing it, but upload `multipart/form-data` should work great i think. And download with `Content-type: octet/stream` + `Content-Disposition: attachment; filename="gs.key"`.

**Comment by mikecarr** [comment]
This has been added to the next branch
