### ISSUE TITLE
Feature-rquest: knob to restart openipc services

### ISSUE THREAD

**Issue by seriyps** [OpenIPC/improver#4]
Would be cool to have some butons to restart (`systemctl restart $service`) OpenIPC services: wfb-ng and pixelpilot. Right now if I change the config file, I need to either restart the Radxa or ssh to it.

**Comment by mikecarr** [comment]
I have been trying to figure out how to send commands to the camera, I'll see if I can add that tonight

**Comment by mikecarr** [comment]
Thoughts? 
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/594b211f-d07a-419b-b826-2b1db4625028">

**Comment by seriyps** [comment]
> I have been trying to figure out how to send commands to the camera, I'll see if I can add that tonight

Well, you'd need the wfb-ng link to air unit for that, which is a bit complex topic...

**Comment by seriyps** [comment]
> Thoughts?

Yes, something like that :+1: 
Please also for wfb-ng!

**Comment by seriyps** [comment]
_On a separate topic - I saw you asked if pixelpilot can print the resolutions the monitor supports explicitly by command, not as part of startup. I think I can add such feature._

**Comment by mikecarr** [comment]
this has been added to next
